myBlog/home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views
from django.urls import path

urlpatterns = [
    #url(r'^$',HomeView.as_view(),name='home')
    path('#', HomeView.post),
]

myBlog/myBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', HomeView.home_view),

    url(r'^post/', include('post.urls')),

]

myBlog/post/urls.py
from django.conf.urls import url
from .views import *

app_name = 'post'

urlpatterns = [
    url(r'^index/', post_index, name='index'),
    url(r'^(?P<id>\d+)/$', post_detail, name='detail'),
    url(r'^create/', post_create, name='create'),
    url(r'^(?P<id>\d+)/update/', post_update, name='update'),
    url(r'^(?P<id>\d+)/delete/', post_delete, name='delete'),

]

myBlog/django/contrib/gis/db/backends/base/models.py
from django.contrib.gis import gdal


class SpatialRefSysMixin:
    """
    The SpatialRefSysMixin is a class used by the database-dependent
    SpatialRefSys objects to reduce redundant code.
    """
    @property
    def srs(self):
        """
        Return a GDAL SpatialReference object.
        """
        # TODO: Is caching really necessary here?  Is complexity worth it?
        if hasattr(self, '_srs'):
            # Returning a clone of the cached SpatialReference object.
            return self._srs.clone()
        else:
            # Attempting to cache a SpatialReference object.

            # Trying to get from WKT first.
            try:
                self._srs = gdal.SpatialReference(self.wkt)
                return self.srs
            except Exception as e:
                msg = e

            try:
                self._srs = gdal.SpatialReference(self.proj4text)
                return self.srs
            except Exception as e:
                msg = e

            raise Exception('Could not get OSR SpatialReference from WKT: %s\nError:\n%s' % (self.wkt, msg))

    @property
    def ellipsoid(self):
        """
        Return a tuple of the ellipsoid parameters:
        (semimajor axis, semiminor axis, and inverse flattening).
        """
        return self.srs.ellipsoid

    @property
    def name(self):
        "Return the projection name."
        return self.srs.name

    @property
    def spheroid(self):
        "Return the spheroid name for this spatial reference."
        return self.srs['spheroid']

    @property
    def datum(self):
        "Return the datum for this spatial reference."
        return self.srs['datum']

    @property
    def projected(self):
        "Is this Spatial Reference projected?"
        return self.srs.projected

    @property
    def local(self):
        "Is this Spatial Reference local?"
        return self.srs.local

    @property
    def geographic(self):
        "Is this Spatial Reference geographic?"
        return self.srs.geographic

    @property
    def linear_name(self):
        "Return the linear units name."
        return self.srs.linear_name

    @property
    def linear_units(self):
        "Return the linear units."
        return self.srs.linear_units

    @property
    def angular_name(self):
        "Return the name of the angular units."
        return self.srs.angular_name

    @property
    def angular_units(self):
        "Return the angular units."
        return self.srs.angular_units

    @property
    def units(self):
        "Return a tuple of the units and the name."
        if self.projected or self.local:
            return (self.linear_units, self.linear_name)
        elif self.geographic:
            return (self.angular_units, self.angular_name)
        else:
            return (None, None)

    @classmethod
    def get_units(cls, wkt):
        """
        Return a tuple of (unit_value, unit_name) for the given WKT without
        using any of the database fields.
        """
        return gdal.SpatialReference(wkt).units

    @classmethod
    def get_spheroid(cls, wkt, string=True):
        """
        Class method used by GeometryField on initialization to
        retrieve the `SPHEROID[..]` parameters from the given WKT.
        """
        srs = gdal.SpatialReference(wkt)
        sphere_params = srs.ellipsoid
        sphere_name = srs['spheroid']

        if not string:
            return sphere_name, sphere_params
        else:
            # `string` parameter used to place in format acceptable by PostGIS
            if len(sphere_params) == 3:
                radius, flattening = sphere_params[0], sphere_params[2]
            else:
                radius, flattening = sphere_params
            return 'SPHEROID["%s",%s,%s]' % (sphere_name, radius, flattening)

    def __str__(self):
        """
        Return the string representation, a 'pretty' OGC WKT.
        """
        return str(self.srs)

myBlog/home/models.py
from django.db import models


class Home(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    title2 = models.CharField(max_length=20, default="")
    encode_name = models.CharField(max_length=100)
    encode_a = models.CharField(max_length=100)
    encode_b = models.CharField(max_length=100)
    encode_t = models.CharField(max_length=100)
    key = models.CharField(max_length=50)
    random_text = models.CharField(max_length=120)
    pub_key_byte = models.CharField(max_length=2000)
    pri_key_byte = models.CharField(max_length=2000)
    encrypt_text = models.CharField(max_length=300)
    decrypt_text = models.CharField(max_length=300)
    dif_key = models.CharField(max_length=2000)

    def __str__(self):
        return self.title

myBlog/home/forms.py
from django import forms


class HomeForm(forms.Form):
    post = forms.CharField()

myBlog/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Home
from .forms import HomeForm
import pydes as pyDes
import rsa
import random
import string

#DES baslangic


def encoder(data, key):
    k = pyDes.des(key[:8], pyDes.CBC, "\0\0\0\0\0\0\0\0", pad=None, padmode=pyDes.PAD_PKCS5)
    d = k.encrypt(data)
    return str(d)[2:-1]


def decoder(data, key):
    k = pyDes.des(key[:8], pyDes.CBC, "\0\0\0\0\0\0\0\0", pad=None, padmode=pyDes.PAD_PKCS5)
    b = bytes(data, "utf-8")
    b = b.decode('unicode-escape').encode('ISO-8859-1')
    return str(k.decrypt(b))[2:-1]

#DES bitis

#random metın baslangic


def random_string(length=100):
    character_set = string.ascii_letters
    return ''.join(random.choice(character_set) for i in range(length))

#random metın baslangic

#rsa icin key uretim baslangic


def create_keys():
    return rsa.newkeys(1024)

#rsa icin key uretim bitis

#rsa metin sifreleme baslangic


def encrypt_msg(msg,pub_key):
    msg = msg.encode('utf-8')
    return rsa.encrypt(msg, pub_key)

#rsa metin sifreleme bitis

#rsa metin desifreleme baslangic


def decrypt_msgs(enc_msg,pri_key):
    enc_msg = rsa.decrypt(enc_msg, pri_key)
    return enc_msg.decode("utf-8")

#rsa metin desifreleme baslangic


class HomeView(TemplateView):
    def home_view(request):
        home = Home.objects.all()
        form = HomeForm()
        (different_pub_key, _) = create_keys()
        #enc_msg = encrypt_msg(home[3].random_text, home[3].pub_key_byte)
        #dex_msg = decrypt.msg(enc.msg, home[3].pri_key_byte)
        context = {
            'isim': 'admin',
            'home_text': home[0].text,
            'home_title': home[0].title,
            'title2': home[0].title2,
            'random_text': home[3].random_text,
            'public_key': home[3].pub_key_byte,
            'private_key': home[3].pri_key_byte,
            'dif_pub_key': home[4].dif_key,
            'encrypt_text': home[4].encrypt_text,
            'decrypt_text': home[4].decrypt_text,

            'enc_name': home[0].encode_name,
            'enc_atext': home[0].encode_a,
            'enc_btext': home[0].encode_b,
            'enc_text': home[0].encode_t,
            'dec_name': decoder(home[0].encode_name, home[0].key),
            'dec_atext': decoder(home[0].encode_a, home[0].key),
            'dec_btext': decoder(home[0].encode_b, home[0].key),
            'dec_text': decoder(home[0].encode_t, home[0].key),
            'key_0': home[0].key,

            'enc_name1': home[1].encode_name,
            'enc_atext1': home[1].encode_a,
            'enc_btext1': home[1].encode_b,
            'enc_text1': home[1].encode_t,
            'dec_name1': decoder(home[1].encode_name, home[1].key),
            'dec_atext1': decoder(home[1].encode_a, home[1].key),
            'dec_btext1': decoder(home[1].encode_b, home[1].key),
            'dec_text1': decoder(home[1].encode_t, home[1].key),
            'key_1': home[1].key,

            'enc_name2': home[2].encode_name,
            'enc_atext2': home[2].encode_a,
            'enc_btext2': home[2].encode_b,
            'enc_text2': home[2].encode_t,
            'dec_name2': decoder(home[2].encode_name, home[2].key),
            'dec_atext2': decoder(home[2].encode_a, home[2].key),
            'dec_btext2': decoder(home[2].encode_b, home[2].key),
            'dec_text2': decoder(home[2].encode_t, home[2].key),
            'key_2': home[2].key,

            'form': form
        }
        return render(request, 'post/index.html', context)

myBlog/templates/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} - Kriptoloji - {% endblock %}</title>
</head>
<body>

    {% include 'header.html' %}
    {% block body %}
    {% endblock %}

</body>
</html>

myBlog/templates/header.html
{%  load static %}
{# <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> #}
{# <link rel="stylesheet" href="{% static 'css/style.css' %}"> #}
{# <script src="{% static 'js/jquery.min.js' %}"></script> #}
{# <script src="{% static 'js/bootstrap.min.js' %}"></script> #}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{# <link rel="stylesheet" href="{% static 'css/style.css' %}"> #}
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">


            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


            <a href="" class="navbar-brand">Kriptoloji</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">


            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Aramak İstedikleriniz.." value="" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>


            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Anasayfa</a></li>
                <li><a href="#">Gönderiler</a></li> {# {% url 'post:index' %} #}
                <li><a href="#">Hakkımda</a></li>
                <li><a href="#">İletişim</a></li>
            </ul>

        </nav>

    </div>
</nav>

myBlog/templates/home.html
{% extends 'base.html' %}

{% block body %}
    {# Merhaba, {{ isim }} #}
{% endblock %}